### ISSUE TITLE
Can not run program

### ISSUE THREAD

**Issue by 123321abccba1** [RBornat/jape#21]
I can not run jape in my computer ,here is error message:

Exception in thread "main" java.awt.AWTError: Assistive Technology not found: com.sun.java.accessibility.AccessBridge
        at java.desktop/java.awt.Toolkit.newAWTError(Toolkit.java:472)
        at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:488)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1620)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:532)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:613)
        at uk.org.jape/uk.org.jape.JapeMenu.<clinit>(JapeMenu.java:732)
        at uk.org.jape/uk.org.jape.Jape.main(Jape.java:136)
Caused by: java.lang.ClassNotFoundException: com.sun.java.accessibility.AccessBridge
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:485)
        ... 13 more

**Comment by haz** [comment]
Maybe this?

https://www.papercut.com/kb/Main/AssistiveTechnologynotfound/

**Comment by RBornat** [comment]
What version of jape? What OS (Windows/Linux/macOS) and what version? What machine? Did it start, or immediately fail? If it started, how much work did you do? What action caused the crash?RSent from my iPhoneOn 5 Sep 2023, at 19:36, 123321abccba1 ***@***.***> wrote:﻿
I can not run jape in my computer ,here is error message:
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: com.sun.java.accessibility.AccessBridge
at java.desktop/java.awt.Toolkit.newAWTError(Toolkit.java:472)
at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:488)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1620)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:532)
at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:613)
at uk.org.jape/uk.org.jape.JapeMenu.(JapeMenu.java:732)
at uk.org.jape/uk.org.jape.Jape.main(Jape.java:136)
Caused by: java.lang.ClassNotFoundException: com.sun.java.accessibility.AccessBridge
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:398)
at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:485)
... 13 more

**Comment by 123321abccba1** [comment]
windows 10

**Comment by 123321abccba1** [comment]
and program immediately fail.

**Comment by RBornat** [comment]
What version of jape? When you downloaded, you picked a version. Sent from my iPhoneOn 5 Sep 2023, at 21:17, 123321abccba1 ***@***.***> wrote:﻿
and program immediately fail.

**Comment by 123321abccba1** [comment]
latest version 9.1.6

**Comment by 123321abccba1** [comment]
It is work！This version I can run in my computer and no warning.

**Comment by 123321abccba1** [comment]
This is working

**Comment by RBornat** [comment]
Wonderful! I’ll release it. All that java seems to do for accessibility is put pop-up text labels on buttons etc. Do you need that?RichardSent from my iPhoneOn 6 Sep 2023, at 17:54, 123321abccba1 ***@***.***> wrote:﻿
This is working

**Comment by 123321abccba1** [comment]
It doesn't affect me much.

**Comment by RBornat** [comment]
closed with release 9.1.7 (fixed)
